import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

type ContentPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  tag: string;
  heroImage?: string;
  body: string;
};

function loadCollection(relativeDir: string): ContentPost[] {
  const dir = path.join(root, relativeDir);
  if (!fs.existsSync(dir)) return [];

  const posts: ContentPost[] = [];

  for (const file of fs.readdirSync(dir)) {
    if (!file.endsWith(".md")) continue;

    const raw = fs.readFileSync(path.join(dir, file), "utf-8");
    const { data, content } = matter(raw);

    if (data.draft === true) {
      console.log(`  skip draft: ${relativeDir}/${file}`);
      continue;
    }

    posts.push({
      slug: file.replace(/\.md$/, ""),
      title: String(data.title ?? "Untitled"),
      description: String(data.description ?? ""),
      date: String(data.date ?? new Date().toISOString()),
      tag: String(data.tag ?? ""),
      heroImage: data.heroImage ? String(data.heroImage) : undefined,
      body: content.trim(),
    });
  }

  return posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

function main() {
  console.log("Generating published content bundle (drafts excluded)…");
  const insights = loadCollection("content/insights");
  const perspectives = loadCollection("content/perspectives");

  const output = `// AUTO-GENERATED by scripts/generate-content.ts — do not edit manually.
// Draft markdown files are never included in this bundle.

export type ContentPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  tag: string;
  heroImage?: string;
  body: string;
};

export type WritingKind = "insight" | "perspective";

export type WritingPost = ContentPost & { kind: WritingKind };

export const insights: ContentPost[] = ${JSON.stringify(insights, null, 2)};

export const perspectives: ContentPost[] = ${JSON.stringify(perspectives, null, 2)};

export function getInsightBySlug(slug: string): ContentPost | undefined {
  return insights.find((item) => item.slug === slug);
}

export function getPerspectiveBySlug(slug: string): ContentPost | undefined {
  return perspectives.find((item) => item.slug === slug);
}

export function getLatestWriting(limit = 3): WritingPost[] {
  const combined: WritingPost[] = [
    ...insights.map((item) => ({ ...item, kind: "insight" as const })),
    ...perspectives.map((item) => ({ ...item, kind: "perspective" as const })),
  ];

  return combined
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit);
}
`;

  const outPath = path.join(root, "src/data/content.generated.ts");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output);
  console.log(`Wrote ${outPath}: ${insights.length} insights, ${perspectives.length} perspectives`);
}

main();
